import { Sparkles, TrendingUp, Lightbulb, ClipboardList, RefreshCw } from "lucide-react";
import { useInsightsSummary } from "@/features/ai-insights/hooks/useInsightsSummary";
import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/ui/card";
import { Button } from "@/shared/components/ui/button";
import { Skeleton } from "@/shared/components/skeletons/skeleton";

export function AiInsightsPage() {
  const { data, isLoading, isError, refetch, isFetching } = useInsightsSummary();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <p className="label-eyebrow">Generated intelligence</p>
          <h1 className="mt-1 font-display text-xl font-semibold text-base-50">AI insights</h1>
        </div>
        <Button variant="secondary" size="sm" onClick={() => refetch()} disabled={isFetching}>
          <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      </div>

      {isError && (
        <div className="rounded-xl2 border border-alert-red/30 bg-alert-red/5 p-6 text-sm text-alert-red">
          Couldn't generate insights right now. The endpoint falls back to a template summary if the
          language model is unavailable — check insights-service logs if this persists.
        </div>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-signal-400" />
            <CardTitle>Crime summary</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? <Skeleton className="h-16 w-full" /> : <p className="text-sm text-base-300">{data?.summary}</p>}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-signal-400" />
            <CardTitle>Trend summary</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? <Skeleton className="h-12 w-full" /> : <p className="text-sm text-base-300">{data?.trendSummary}</p>}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <ClipboardList className="h-4 w-4 text-signal-400" />
              <CardTitle>Top findings</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
                <Skeleton className="h-4 w-4/6" />
              </div>
            ) : (
              <ul className="space-y-2.5">
                {data?.topFindings.map((f, i) => (
                  <li key={i} className="flex gap-2.5 text-sm text-base-300">
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-signal-400" />
                    {f}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Lightbulb className="h-4 w-4 text-alert-amber" />
              <CardTitle>Recommendations</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-5/6" />
                <Skeleton className="h-4 w-4/6" />
              </div>
            ) : (
              <ul className="space-y-2.5">
                {data?.recommendations.map((r, i) => (
                  <li key={i} className="flex gap-2.5 text-sm text-base-300">
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-alert-amber" />
                    {r}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      <p className="text-center text-xs text-base-500">
        Generated by the platform's language model from live aggregate data — not a substitute for analyst review.
      </p>
    </div>
  );
}
